import type { Metadata } from 'next';

import Footer from '@/components/ui/Footer';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: '映画サークル',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="h-full w-full overflow-x-hidden">
        {children}
        <Footer />
      </body>
    </html>
  );
}
