services:
  app-dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      network: host
    volumes:
      - ./../:/app:cached
    command: sleep infinity
    networks:
      - dev_network

networks:
  dev_network:
    name: dev_network
    driver: bridge
